server:
  port: 8689

db:
  host: localhost
  schema: customer
  username: sys_customer
  password: customer_6#233zJMNTjkQb#sgps#
  port: 3366

aws:
  resources:
    sqs:
      remove-customer-data.queue: local-customer-remove-customer-data-queue
      customer-removed-data.queue: local-customer-remove-data-response-queue
    sns:
      customer-remove-data.topic: local-customer-remove-data-topic
    s3:
      customer.data.removal: customer-data-removal

customer.data.removal.aes:
  algorithm: AES/CBC/PKCS5PADDING
  password: 5110569f-7666-4c67-98e5-db8d6e1b
  iv: e2a3c25441d4f75e

spring:
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1