name: Create Project Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create New Release
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available

      - name: Build Project
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build

      - name: Create Release Tag
        id: tag_release
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
        run: |
          ./gradlew release \
            -Prelease.customUsername=${{ GITHUB_ACTOR }} \
            -Prelease.customPassword=${{ GITHUB_TOKEN }}

      - name: Get Current Release Tag
        run: echo "RELEASE_NAME=$(./gradlew cV -q -Prelease.quiet)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.JAVA_TOKEN }}
          name: ${{ RELEASE_NAME }}
          tag_name: ${{ RELEASE_NAME }}