name: Build and Push Docker Image to Docker Hub

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Validating Code for Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:

        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
    
      - id: gradle_build
        name: Execute Gradle build
        run: ./gradlew build

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}